import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import SuccessPopup from "./SuccessPopup";  

export default function PopupPage({ isOpen, onClose, password }) {
  const [email, setEmail] = useState("");
  const [showSuccess, setShowSuccess] = useState(false);

  const handleSend = async () => {
    if (!email) {
      alert("⚠️ Please enter your email!");
      return;
    }

    try {
      const response = await fetch("/api/send", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email, password }),
      });

      const data = await response.json();
      console.log("✅ Response:", data);
      if (response.ok) {
        setShowSuccess(true); // show success popup when email sent successfully
        setEmail("");
      } else {
        alert("❌ Failed to send email. Please try again.");
      }
    } catch (error) {
      console.error("❌ Error:", error);
    }
  };

  return (
    <>
      {/* Input Popup */}
      <AnimatePresence>
        {isOpen && (
          <motion.div
            className="fixed inset-0 bg-black bg-opacity-40 flex items-center justify-center z-50"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
          >
            <motion.div
              className="bg-black rounded-2xl shadow-2xl shadow-gray-600 p-6 w-96 text-center"
              initial={{ scale: 0.8, opacity: 0, y: -50 }}
              animate={{ scale: 1, opacity: 1, y: 0 }}
              exit={{ scale: 0.8, opacity: 0, y: 50 }}
            >
              <h1 className="text-xl font-bold mb-4 text-white">
                Send password to your email
              </h1>

              <input
                type="email"
                placeholder="Enter your email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                className="w-full p-3 border rounded-xl mb-4 bg-gray-100 font-bold text-gray-900"
              />

              <motion.p
                className="text-sm text-gray-800 bg-yellow-100 border border-yellow-300 rounded-lg px-3 py-2 mb-6"
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.4 }}
              >
                ⚡ We don’t ever save your any kind of password in our database.
                It is totally secure and generated by satellite.
              </motion.p>

              <button
                onClick={handleSend}
                className="w-full bg-blue-600 hover:bg-blue-700 text-white py-2 rounded-xl mb-4"
              >
                Send
              </button>

              <button
                onClick={() => {
                  onClose();
                  setPassWord("");
                }}
                className="bg-red-500 hover:bg-red-600 text-white px-6 py-2 rounded-xl"
              >
                Close
              </button>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* ✅ Success Popup */}
      <SuccessPopup
        isOpen={showSuccess}
        onClose={() => setShowSuccess(false)}
      />
    </>
  );
}